plugins {
    id 'java'
    id 'application'
}

group = 'com.disha'
version = '1.0'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.8.1'
}

test {
    useJUnitPlatform()
}

application {
    mainClass = '' // Optional, leave blank if you're not building a CLI app
}
